# Generated by Django 4.2.15 on 2024-12-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collegemanagement', '0001_initial'),
        ('coursemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the inquirer.', max_length=255)),
                ('email', models.EmailField(help_text='Email address of the inquirer.', max_length=254)),
                ('phone', models.CharField(help_text='Phone number of the inquirer.', max_length=15)),
                ('message', models.TextField(blank=True, help_text='Message or query from the user.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time when the inquiry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The last time the inquiry was updated.')),
                ('colleges', models.ManyToManyField(help_text='Colleges the user is interested in.', related_name='inquiries', to='collegemanagement.college')),
                ('courses', models.ManyToManyField(help_text='Courses the user is interested in.', related_name='inquiries', to='coursemanagement.course')),
            ],
        ),
    ]
