# Generated by Django 4.2.17 on 2025-03-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_alter_inquiry_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
