# Generated by Django 4.2.17 on 2025-04-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0026_alter_college_affiliated_alter_college_college_type_and_more'),
        ('coursemanagement', '0012_alter_course_canonical_url_alter_course_og_url'),
        ('inquiry', '0003_rename_created_at_inquiry_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='colleges',
            field=models.ManyToManyField(blank=True, help_text='Colleges the user is interested in.', related_name='inquiries', to='collegemanagement.college'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Courses the user is interested in.', related_name='inquiries', to='coursemanagement.course'),
        ),
    ]
