# Generated by Django 4.2.15 on 2024-09-26 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('level', '0001_initial'),
        ('affiliation', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('excerpt', models.TextField()),
                ('image', models.ImageField(upload_to='courses/images/')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('affiliations', models.ManyToManyField(to='affiliation.affiliation')),
                ('faculties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_faculties', to='faculty.faculty')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_level', to='level.level')),
            ],
        ),
    ]
