# Generated by Django 4.2.15 on 2024-12-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('level', '__first__'),
        ('duration', '__first__'),
        ('faculty', '__first__'),
        ('discipline', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Title for search engines.', max_length=255, null=True)),
                ('meta_tag', models.CharField(blank=True, help_text='Primary meta tag for SEO.', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Short description for SEO.', null=True)),
                ('meta_keywords', models.TextField(blank=True, help_text='Comma-separated keywords for SEO.', null=True)),
                ('meta_author', models.CharField(blank=True, help_text='Author information for SEO.', max_length=255, null=True)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content.', null=True)),
                ('og_title', models.CharField(blank=True, help_text='Title for social sharing.', max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Description for social sharing.', null=True)),
                ('og_url', models.URLField(blank=True, help_text='URL to share on social platforms.', null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='college/og_image/')),
                ('og_type', models.CharField(blank=True, help_text='Type of the OG content (e.g., website, article).', max_length=50, null=True)),
                ('og_locale', models.CharField(blank=True, default='en_US', help_text='Locale for OG tags (e.g., en_US).', max_length=10, null=True)),
                ('dc_title', models.CharField(blank=True, help_text='Title for Dublin Core Metadata.', max_length=255, null=True)),
                ('dc_description', models.TextField(blank=True, help_text='Description for Dublin Core Metadata.', null=True)),
                ('dc_language', models.CharField(blank=True, default='en', help_text='Language code for Dublin Core Metadata (e.g., en, fr).', max_length=10, null=True)),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('course_shortdescription', models.TextField(default='')),
                ('course_outcome', models.TextField(default='')),
                ('course_curriculum', models.TextField(default='')),
                ('eligibility_criteria', models.TextField(default='')),
                ('image', models.ImageField(upload_to='courses/images/')),
                ('curriculum_file_upload', models.FileField(upload_to='courses/pdf/')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('discipline', models.ManyToManyField(related_name='course_discipline', to='discipline.discipline')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_duration', to='duration.duration')),
                ('faculties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_faculties', to='faculty.faculty')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_level', to='level.level')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
