# Generated by Django 4.2.15 on 2024-12-05 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '__first__'),
        ('duration', '__first__'),
        ('discipline', '__first__'),
        ('affiliation', '0001_initial'),
        ('level', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('course_shortdescription', models.TextField(default='')),
                ('course_outcome', models.TextField(default='')),
                ('course_curriculum', models.TextField(default='')),
                ('eligibility_criteria', models.TextField(default='')),
                ('image', models.ImageField(upload_to='courses/images/')),
                ('curriculum_file_upload', models.FileField(upload_to='courses/pdf/')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_affiliations', to='affiliation.affiliation')),
                ('discipline', models.ManyToManyField(related_name='course_discipline', to='discipline.discipline')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_duration', to='duration.duration')),
                ('faculties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_faculties', to='faculty.faculty')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_level', to='level.level')),
            ],
        ),
    ]
