# Generated by Django 4.2.15 on 2024-12-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
        ('coursemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='abbreviation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.ManyToManyField(to='discipline.discipline'),
        ),
    ]
