# Generated by Django 4.2.17 on 2025-01-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0002_alter_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='curriculum_file_upload',
            field=models.FileField(blank=True, null=True, upload_to='courses/pdf/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/'),
        ),
    ]
