# Generated by Django 4.2.15 on 2024-12-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0002_course_canonical_url_course_dc_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='affiliation',
        ),
    ]
