# Generated by Django 4.2.15 on 2024-12-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0001_initial'),
        ('discipline', '0001_initial'),
        ('coursemanagement', '0002_course_abbreviation_course_discipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='course',
            name='course_curriculum',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='course_outcome',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='course_shortdescription',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum_file_upload',
            field=models.FileField(default='', upload_to='courses/pdf/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='eligibility_criteria',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='affiliations',
            field=models.ManyToManyField(related_name='course_affiliations', to='affiliation.affiliation'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='discipline',
            field=models.ManyToManyField(related_name='course_discipline', to='discipline.discipline'),
        ),
    ]
