# Generated by Django 4.2.17 on 2025-01-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0003_alter_course_curriculum_file_upload_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='faculties',
            new_name='faculty',
        ),
    ]
