# Generated by Django 4.2.15 on 2024-12-04 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duration', '0001_initial'),
        ('affiliation', '0001_initial'),
        ('coursemanagement', '0003_remove_course_excerpt_course_course_curriculum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='affiliations',
        ),
        migrations.AddField(
            model_name='course',
            name='affiliation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='course_affiliations', to='affiliation.affiliation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_duration', to='duration.duration'),
        ),
    ]
