# Generated by Django 4.2.17 on 2025-01-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0003_alter_affiliation_established_year'),
        ('coursemanagement', '0004_rename_faculties_course_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_affiliation', to='affiliation.affiliation'),
        ),
    ]
