# Generated by Django 4.2.17 on 2025-01-30 04:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0005_course_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
