# Generated by Django 4.2.17 on 2025-02-06 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0007_alter_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='curriculum_file_upload',
        ),
        migrations.CreateModel(
            name='CourseCurriculumFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_file_upload', models.FileField(upload_to='courses/curriculum_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_files', to='coursemanagement.course')),
            ],
        ),
    ]
