# Generated by Django 4.2.17 on 2025-02-12 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0008_remove_course_curriculum_file_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecurriculumfile',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_file_upload', to='coursemanagement.course'),
        ),
    ]
