# Generated by Django 4.2.17 on 2025-02-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0009_alter_coursecurriculumfile_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecurriculumfile',
            options={'permissions': [('manage_coursecurriculumfile', 'Manage manage_coursecurriculumfile')]},
        ),
    ]
