# Generated by Django 4.2.17 on 2025-06-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
