# Generated by Django 4.2.17 on 2025-02-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestsubmission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestsubmission',
            options={'permissions': [('manage_requestsubmission', 'Manage Request Submission')]},
        ),
    ]
