# Generated by Django 4.2.17 on 2025-04-15 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requestsubmission', '0002_alter_requestsubmission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_submission', to=settings.AUTH_USER_MODEL),
        ),
    ]
