# Generated by Django 4.2.15 on 2024-12-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='url',
            new_name='link',
        ),
    ]
