# Generated by Django 4.2.17 on 2025-02-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_alter_socialmedia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'permissions': [('manage_socialmedia', 'Manage Social Media')]},
        ),
    ]
