# Generated by Django 4.2.17 on 2025-02-18 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0013_alter_college_social_media'),
        ('socialmedia', '0003_alter_socialmedia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_socialmedia', to='collegemanagement.college')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_socialmedia', to='socialmedia.socialmedia')),
            ],
        ),
    ]
