# Generated by Django 4.2.17 on 2025-02-18 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0014_remove_college_social_media'),
        ('socialmedia', '0004_collegesocialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegesocialmedia',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_socialmedia', to='collegemanagement.college'),
        ),
        migrations.AlterField(
            model_name='collegesocialmedia',
            name='social_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_socialmedia', to='socialmedia.socialmedia'),
        ),
    ]
