# Generated by Django 4.2.17 on 2025-02-18 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0005_alter_collegesocialmedia_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegesocialmedia',
            name='social_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='socialmedia.socialmedia'),
        ),
    ]
