# Generated by Django 4.2.17 on 2025-02-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0006_alter_collegesocialmedia_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegesocialmedia',
            name='social_media',
        ),
        migrations.AddField(
            model_name='collegesocialmedia',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='components/banner'),
        ),
        migrations.AddField(
            model_name='collegesocialmedia',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collegesocialmedia',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collegesocialmedia',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
