# Generated by Django 4.2.17 on 2025-02-18 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0014_remove_college_social_media'),
        ('socialmedia', '0007_remove_collegesocialmedia_social_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegesocialmedia',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='collegemanagement.college'),
        ),
    ]
