# Generated by Django 4.2.17 on 2025-02-18 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0008_alter_collegesocialmedia_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegesocialmedia',
            name='name',
        ),
        migrations.AddField(
            model_name='collegesocialmedia',
            name='social_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='socialmedia.socialmedia'),
        ),
    ]
