# Generated by Django 4.2.17 on 2025-02-18 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0009_remove_collegesocialmedia_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegesocialmedia',
            old_name='social_media',
            new_name='name',
        ),
    ]
