# Generated by Django 4.2.17 on 2025-03-02 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0021_remove_college_facilities'),
        ('socialmedia', '0010_rename_social_media_collegesocialmedia_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegesocialmedia',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_social_media', to='collegemanagement.college'),
        ),
    ]
