# Generated by Django 4.2.17 on 2025-03-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0011_alter_collegesocialmedia_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
