# Generated by Django 4.2.15 on 2024-12-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegetype', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegetype',
            options={'permissions': [('manage_college_type', 'Manage college type')]},
        ),
    ]
