# Generated by Django 4.2.17 on 2025-02-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegetype', '0002_alter_collegetype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegetype',
            options={'permissions': [('manage_collegetype', 'Manage college type')]},
        ),
    ]
