# Generated by Django 4.2.17 on 2025-03-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetype', '0003_alter_collegetype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegetype',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
