# Generated by Django 4.2.15 on 2024-09-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/'),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
