# Generated by Django 4.2.15 on 2024-12-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formprogress', '0003_formstepprogress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formstepprogress',
            name='user',
        ),
    ]
