# Generated by Django 4.2.15 on 2024-12-05 06:11

import affiliation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '__first__'),
        ('certification', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('established_year', models.IntegerField(default=2024, validators=[affiliation.models.validate_year])),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('google_map_embed_url', models.URLField(blank=True, max_length=500, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('university_type', models.CharField(choices=[('local', 'Local'), ('foreign', 'Foreign')], default='local', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='affiliation_image/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='affiliation_image/')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('certification', models.ManyToManyField(related_name='affiliation_certification', to='certification.certification')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_district', to='district.district')),
            ],
        ),
    ]
