# Generated by Django 4.2.15 on 2024-12-08 06:11

import affiliation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certification', '__first__'),
        ('district', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Title for search engines.', max_length=255, null=True)),
                ('meta_tag', models.CharField(blank=True, help_text='Primary meta tag for SEO.', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Short description for SEO.', null=True)),
                ('meta_keywords', models.TextField(blank=True, help_text='Comma-separated keywords for SEO.', null=True)),
                ('meta_author', models.CharField(blank=True, help_text='Author information for SEO.', max_length=255, null=True)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content.', null=True)),
                ('og_title', models.CharField(blank=True, help_text='Title for social sharing.', max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Description for social sharing.', null=True)),
                ('og_url', models.URLField(blank=True, help_text='URL to share on social platforms.', null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='college/og_image/')),
                ('og_type', models.CharField(blank=True, help_text='Type of the OG content (e.g., website, article).', max_length=50, null=True)),
                ('og_locale', models.CharField(blank=True, default='en_US', help_text='Locale for OG tags (e.g., en_US).', max_length=10, null=True)),
                ('dc_title', models.CharField(blank=True, help_text='Title for Dublin Core Metadata.', max_length=255, null=True)),
                ('dc_description', models.TextField(blank=True, help_text='Description for Dublin Core Metadata.', null=True)),
                ('dc_language', models.CharField(blank=True, default='en', help_text='Language code for Dublin Core Metadata (e.g., en, fr).', max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('established_year', models.IntegerField(default=2024, validators=[affiliation.models.validate_year])),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('google_map_embed_url', models.URLField(blank=True, max_length=500, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('university_type', models.CharField(choices=[('local', 'Local'), ('foreign', 'Foreign')], default='local', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='affiliation_image/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='affiliation_image/')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('certification', models.ManyToManyField(related_name='affiliation_certification', to='certification.certification')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_district', to='district.district')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
