# Generated by Django 4.2.15 on 2024-09-26 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '__first__'),
        ('college', '__first__'),
        ('level', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('established_year', models.IntegerField(default=2024)),
                ('google_map_embed_url', models.URLField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('salient_features', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='affiliation_image/')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='affiliation_files/')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('affiliated_colleges', models.ManyToManyField(related_name='affiliations_college', to='college.college')),
                ('level', models.ManyToManyField(related_name='affiliations_level', to='level.level')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_location', to='location.location')),
            ],
        ),
    ]
