# Generated by Django 4.2.15 on 2024-09-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
        ('college', '0001_initial'),
        ('course', '0001_initial'),
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='affiliated_colleges',
            field=models.ManyToManyField(related_name='affiliations_college', to='college.college'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='courses',
            field=models.ManyToManyField(related_name='affiliations_courses', to='course.course'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='established_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='affiliation_image/'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='affiliation_files/'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='google_map_embed_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='level',
            field=models.ManyToManyField(related_name='affiliations_level', to='level.level'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='location',
            field=models.CharField(blank=True, choices=[('foreign', 'Foreign'), ('domestic', 'Domestic')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='salient_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='website_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
