# Generated by Django 4.2.15 on 2024-12-04 09:04

import affiliation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
        ('collegetype', '0001_initial'),
        ('certification', '0001_initial'),
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliation',
            old_name='feature_image',
            new_name='cover_image',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='affiliated_colleges',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='level',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='salient_features',
        ),
        migrations.AddField(
            model_name='affiliation',
            name='certification',
            field=models.ManyToManyField(related_name='affiliation_certification', to='certification.certification'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='district',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_district', to='district.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliation',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='affiliation_image/'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='university_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_type', to='collegetype.collegetype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='established_year',
            field=models.IntegerField(default=2024, validators=[affiliation.models.validate_year]),
        ),
    ]
