# Generated by Django 4.2.15 on 2024-09-24 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('affiliation', '0002_affiliation_address_affiliation_affiliated_colleges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_location', to='location.location'),
            preserve_default=False,
        ),
    ]
