# Generated by Django 4.2.15 on 2024-12-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0002_rename_feature_image_affiliation_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='university_type',
            field=models.CharField(choices=[('local', 'Local'), ('foreign', 'Foreign')], default='local', max_length=10),
        ),
    ]
