# Generated by Django 4.2.17 on 2025-01-27 04:29

import affiliation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0002_alter_affiliation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='established_year',
            field=models.IntegerField(default=2025, validators=[affiliation.models.validate_year]),
        ),
    ]
