# Generated by Django 4.2.17 on 2025-02-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0005_alter_affiliation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
