# Generated by Django 4.2.17 on 2025-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0007_alter_affiliation_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='google_map_embed_url',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='website_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
