# Generated by Django 4.2.17 on 2025-03-25 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0003_rename_is_shown_district_is_show'),
        ('affiliation', '0008_alter_affiliation_google_map_embed_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_district', to='district.district'),
        ),
    ]
