# Generated by Django 4.2.17 on 2025-03-26 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0003_rename_is_shown_district_is_show'),
        ('affiliation', '0009_alter_affiliation_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_district', to='district.district'),
        ),
    ]
