# Generated by Django 4.2.15 on 2024-12-08 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursemanagement', '0001_initial'),
        ('faculty', '0001_initial'),
        ('affiliation', '0001_initial'),
        ('level', '__first__'),
        ('collegemanagement', '0001_initial'),
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Title for search engines.', max_length=255, null=True)),
                ('meta_tag', models.CharField(blank=True, help_text='Primary meta tag for SEO.', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Short description for SEO.', null=True)),
                ('meta_keywords', models.TextField(blank=True, help_text='Comma-separated keywords for SEO.', null=True)),
                ('meta_author', models.CharField(blank=True, help_text='Author information for SEO.', max_length=255, null=True)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content.', null=True)),
                ('og_title', models.CharField(blank=True, help_text='Title for social sharing.', max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Description for social sharing.', null=True)),
                ('og_url', models.URLField(blank=True, help_text='URL to share on social platforms.', null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='college/og_image/')),
                ('og_type', models.CharField(blank=True, help_text='Type of the OG content (e.g., website, article).', max_length=50, null=True)),
                ('og_locale', models.CharField(blank=True, default='en_US', help_text='Locale for OG tags (e.g., en_US).', max_length=10, null=True)),
                ('dc_title', models.CharField(blank=True, help_text='Title for Dublin Core Metadata.', max_length=255, null=True)),
                ('dc_description', models.TextField(blank=True, help_text='Description for Dublin Core Metadata.', null=True)),
                ('dc_language', models.CharField(blank=True, default='en', help_text='Language code for Dublin Core Metadata (e.g., en, fr).', max_length=10, null=True)),
                ('title', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField()),
                ('active_period_start', models.DateField()),
                ('active_period_end', models.DateField()),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('affiliation', models.ManyToManyField(to='affiliation.affiliation')),
                ('college', models.ManyToManyField(blank=True, to='collegemanagement.college')),
                ('course', models.ManyToManyField(blank=True, to='coursemanagement.course')),
                ('district', models.ManyToManyField(blank=True, to='district.district')),
                ('faculty', models.ManyToManyField(blank=True, to='faculty.faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_show', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='information_category/')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='information_category/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformationTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_show', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='information_tagging/')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformationFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='information_docs/')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_files', to='informationmanagement.information')),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='image',
            field=models.ManyToManyField(blank=True, to='informationmanagement.informationgallery'),
        ),
        migrations.AddField(
            model_name='information',
            name='information_category',
            field=models.ManyToManyField(blank=True, to='informationmanagement.informationcategory'),
        ),
        migrations.AddField(
            model_name='information',
            name='information_tagging',
            field=models.ManyToManyField(blank=True, to='informationmanagement.informationtagging'),
        ),
        migrations.AddField(
            model_name='information',
            name='level',
            field=models.ManyToManyField(blank=True, to='level.level'),
        ),
        migrations.AddField(
            model_name='information',
            name='sublevel',
            field=models.ManyToManyField(blank=True, to='level.sublevel'),
        ),
    ]
