# Generated by Django 4.2.15 on 2024-12-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_sublevel'),
        ('informationmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='information_docs/')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='information_category/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='information',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='information',
            name='college_level_type',
        ),
        migrations.RemoveField(
            model_name='information',
            name='course_level_type',
        ),
        migrations.RemoveField(
            model_name='information',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='information',
            name='is_view',
        ),
        migrations.RemoveField(
            model_name='information',
            name='semesters',
        ),
        migrations.RemoveField(
            model_name='information',
            name='template_name',
        ),
        migrations.RemoveField(
            model_name='information',
            name='years',
        ),
        migrations.AddField(
            model_name='information',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content.', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='dc_description',
            field=models.TextField(blank=True, help_text='Description for Dublin Core Metadata.', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='dc_language',
            field=models.CharField(blank=True, default='en', help_text='Language code for Dublin Core Metadata (e.g., en, fr).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='dc_title',
            field=models.CharField(blank=True, help_text='Title for Dublin Core Metadata.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='meta_author',
            field=models.CharField(blank=True, help_text='Author information for SEO.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Short description for SEO.', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for SEO.', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='meta_tag',
            field=models.CharField(blank=True, help_text='Primary meta tag for SEO.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Title for search engines.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for social sharing.', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='college/og_image/'),
        ),
        migrations.AddField(
            model_name='information',
            name='og_locale',
            field=models.CharField(blank=True, default='en_US', help_text='Locale for OG tags (e.g., en_US).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title for social sharing.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='og_type',
            field=models.CharField(blank=True, help_text='Type of the OG content (e.g., website, article).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='og_url',
            field=models.URLField(blank=True, help_text='URL to share on social platforms.', null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='sublevel',
            field=models.ManyToManyField(blank=True, to='level.sublevel'),
        ),
        migrations.RemoveField(
            model_name='information',
            name='image',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.AddField(
            model_name='information',
            name='file',
            field=models.ManyToManyField(blank=True, to='informationmanagement.informationfiles'),
        ),
        migrations.AddField(
            model_name='information',
            name='image',
            field=models.ManyToManyField(blank=True, to='informationmanagement.informationgallery'),
        ),
    ]
