# Generated by Django 4.2.15 on 2024-12-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informationmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'permissions': [('manage_information', 'Manage Information')]},
        ),
        migrations.AlterModelOptions(
            name='informationcategory',
            options={'permissions': [('manage_information_category', 'Manage Information Category')]},
        ),
        migrations.AlterModelOptions(
            name='informationfiles',
            options={'permissions': [('manage_information_files', 'Manage Information Files')]},
        ),
        migrations.AlterModelOptions(
            name='informationgallery',
            options={'permissions': [('manage_information_gallery', 'Manage Information Gallery')]},
        ),
        migrations.AlterModelOptions(
            name='informationtagging',
            options={'permissions': [('manage_information_tagging', 'Manage Information Tagging')]},
        ),
    ]
