# Generated by Django 4.2.15 on 2024-09-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeleveltype', '0001_initial'),
        ('certification', '0001_initial'),
        ('informationmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='certification',
            field=models.ManyToManyField(blank=True, to='certification.certification'),
        ),
        migrations.AddField(
            model_name='information',
            name='college_level_type',
            field=models.ManyToManyField(blank=True, to='collegeleveltype.collegeleveltype'),
        ),
        migrations.AddField(
            model_name='information',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='information',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='information',
            name='template_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='informationcategory',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='informationcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='information_category/'),
        ),
        migrations.AddField(
            model_name='informationcategory',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informationcategory',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='informationtagging',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='informationtagging',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='information_tagging/'),
        ),
        migrations.AddField(
            model_name='informationtagging',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informationtagging',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='informationtagging',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='information_images/'),
        ),
        migrations.AlterField(
            model_name='informationtagging',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
