# Generated by Django 4.2.15 on 2024-12-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0002_remove_college_college_admin'),
        ('informationmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='college',
            field=models.ManyToManyField(blank=True, to='collegemanagement.college'),
        ),
    ]
