# Generated by Django 4.2.15 on 2024-12-06 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informationmanagement', '0002_information_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='college_type',
        ),
        migrations.RemoveField(
            model_name='information',
            name='file',
        ),
        migrations.AddField(
            model_name='informationfiles',
            name='information',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='information_files', to='informationmanagement.information'),
            preserve_default=False,
        ),
    ]
