# Generated by Django 4.2.15 on 2024-12-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationmanagement', '0002_alter_information_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
