# Generated by Django 4.2.15 on 2024-12-09 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informationmanagement', '0003_information_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='image',
        ),
        migrations.AddField(
            model_name='informationgallery',
            name='information',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='information_gallery', to='informationmanagement.information'),
            preserve_default=False,
        ),
    ]
