# Generated by Django 4.2.17 on 2025-01-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationmanagement', '0004_remove_information_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=510),
        ),
    ]
