# Generated by Django 4.2.17 on 2025-01-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationmanagement', '0007_alter_information_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
