# Generated by Django 4.2.17 on 2025-02-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informationmanagement', '0008_alter_information_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationfiles',
            options={'permissions': [('manage_informationfiles', 'Manage Information Files')]},
        ),
        migrations.AlterModelOptions(
            name='informationgallery',
            options={'permissions': [('manage_informationgallery', 'Manage Information Gallery')]},
        ),
    ]
