# Generated by Django 4.2.17 on 2025-02-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationmanagement', '0009_alter_informationfiles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='active_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='active_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
