# Generated by Django 4.2.17 on 2025-02-21 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('informationmanagement', '0010_alter_information_active_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationcategory',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='informationcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
