# Generated by Django 4.2.17 on 2025-03-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationmanagement', '0011_informationcategory_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='featured_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
