# Generated by Django 4.2.15 on 2024-12-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='description',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='image',
        ),
    ]
