# Generated by Django 4.2.17 on 2025-02-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('featured_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='gallery/feature_images')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'permissions': [('manage_album', 'Manage Album')],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='gallery/images')),
                ('is_cover', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='gallery.album')),
            ],
            options={
                'permissions': [('manage_gallery', 'Manage Gallery')],
            },
        ),
    ]
