# Generated by Django 4.2.15 on 2024-12-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'permissions': [('manage_album', 'Manage Album')]},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'permissions': [('manage_gallery', 'Manage Gallery')]},
        ),
    ]
