# Generated by Django 4.2.15 on 2024-12-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
    ]
