# Generated by Django 4.2.17 on 2025-02-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='featured_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
