# Generated by Django 4.2.17 on 2025-01-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_album_options_alter_gallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='featured_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='gallery/feature_images'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='gallery/images'),
        ),
    ]
