# Generated by Django 4.2.15 on 2024-12-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_gallery_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
