# Generated by Django 4.2.15 on 2024-12-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='facility_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
