# Generated by Django 4.2.17 on 2025-01-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_alter_facility_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
