# Generated by Django 4.2.17 on 2025-02-27 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0021_remove_college_facilities'),
        ('facilities', '0003_facility_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_facilities', to='collegemanagement.college')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_facilities', to='facilities.facility')),
            ],
            options={
                'permissions': [('manage_collegefacility', 'Manage collegefacility')],
            },
        ),
    ]
