# Generated by Django 4.2.15 on 2024-12-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discipline', '__first__'),
        ('socialmedia', '0001_initial'),
        ('affiliation', '0001_initial'),
        ('facilities', '__first__'),
        ('collegetype', '__first__'),
        ('district', '__first__'),
        ('formprogress', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Title for search engines.', max_length=255, null=True)),
                ('meta_tag', models.CharField(blank=True, help_text='Primary meta tag for SEO.', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Short description for SEO.', null=True)),
                ('meta_keywords', models.TextField(blank=True, help_text='Comma-separated keywords for SEO.', null=True)),
                ('meta_author', models.CharField(blank=True, help_text='Author information for SEO.', max_length=255, null=True)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content.', null=True)),
                ('og_title', models.CharField(blank=True, help_text='Title for social sharing.', max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Description for social sharing.', null=True)),
                ('og_url', models.URLField(blank=True, help_text='URL to share on social platforms.', null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='college/og_image/')),
                ('og_type', models.CharField(blank=True, help_text='Type of the OG content (e.g., website, article).', max_length=50, null=True)),
                ('og_locale', models.CharField(blank=True, default='en_US', help_text='Locale for OG tags (e.g., en_US).', max_length=10, null=True)),
                ('dc_title', models.CharField(blank=True, help_text='Title for Dublin Core Metadata.', max_length=255, null=True)),
                ('dc_description', models.TextField(blank=True, help_text='Description for Dublin Core Metadata.', null=True)),
                ('dc_language', models.CharField(blank=True, default='en', help_text='Language code for Dublin Core Metadata (e.g., en, fr).', max_length=10, null=True)),
                ('banner_image', models.ImageField(upload_to='college/banner/')),
                ('dp_image', models.ImageField(upload_to='college/dp/')),
                ('name', models.CharField(max_length=255)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('about', models.TextField()),
                ('brochure', models.FileField(blank=True, null=True, upload_to='college/brochure/')),
                ('placement', models.TextField(blank=True, null=True)),
                ('scholarship', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('affiliated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_affiliation', to='affiliation.affiliation')),
                ('college_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_type', to='collegetype.collegetype')),
                ('discipline', models.ManyToManyField(related_name='college_discipline', to='discipline.discipline')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_district', to='district.district')),
                ('facilities', models.ManyToManyField(related_name='college_facilities', to='facilities.facility')),
                ('social_media', models.ManyToManyField(to='socialmedia.socialmedia')),
                ('step_counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_counter', to='formprogress.formstepprogress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollegeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='college/gallery/')),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeFaqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_faq', to='collegemanagement.college')),
            ],
        ),
    ]
