# Generated by Django 4.2.15 on 2024-09-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collegetype', '0002_collegetype_description_collegetype_image_and_more'),
        ('admissionopen', '0001_initial'),
        ('facilities', '0001_initial'),
        ('location', '0001_initial'),
        ('affiliation', '0002_affiliation_address_affiliation_affiliated_colleges_and_more'),
        ('coursesandfees', '0001_initial'),
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='college/gallery/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='college/banner/')),
                ('dp_image', models.ImageField(upload_to='college/dp/')),
                ('name', models.CharField(max_length=255)),
                ('established_date', models.DateField()),
                ('website_link', models.URLField()),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('about', models.TextField()),
                ('featured_video', models.URLField(blank=True, null=True)),
                ('brochure', models.FileField(upload_to='college/brochure/')),
                ('admission_open', models.ManyToManyField(to='admissionopen.admissionopen')),
                ('affiliated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliation.affiliation')),
                ('college_gallery', models.ManyToManyField(to='collegemanagement.collegegallery')),
                ('college_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegetype.collegetype')),
                ('courses_and_fees', models.ManyToManyField(to='coursesandfees.coursesandfees')),
                ('facilities', models.ManyToManyField(to='facilities.facility')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('social_media', models.ManyToManyField(to='socialmedia.socialmedia')),
            ],
        ),
    ]
