# Generated by Django 4.2.15 on 2024-12-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'permissions': [('manage_college', 'Manage college')]},
        ),
        migrations.AlterModelOptions(
            name='collegefaqs',
            options={'permissions': [('manage_faq', 'Manage faq')]},
        ),
        migrations.AlterModelOptions(
            name='collegegallery',
            options={'permissions': [('manage_college_gallery', 'Manage college gallery')]},
        ),
        migrations.AlterModelOptions(
            name='placement',
            options={'permissions': [('manage_placement', 'Manage placement')]},
        ),
    ]
