# Generated by Django 4.2.15 on 2024-12-04 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
        ('collegetype', '0001_initial'),
        ('discipline', '0001_initial'),
        ('affiliation', '0001_initial'),
        ('collegemanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='admission_open',
        ),
        migrations.RemoveField(
            model_name='college',
            name='brochure',
        ),
        migrations.RemoveField(
            model_name='college',
            name='college_gallery',
        ),
        migrations.RemoveField(
            model_name='college',
            name='courses_and_fees',
        ),
        migrations.RemoveField(
            model_name='college',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='college',
            name='featured_video',
        ),
        migrations.RemoveField(
            model_name='college',
            name='location',
        ),
        migrations.RemoveField(
            model_name='college',
            name='scholarships',
        ),
        migrations.AddField(
            model_name='college',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content.', null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='discipline',
            field=models.ManyToManyField(related_name='college_discipline', to='discipline.discipline'),
        ),
        migrations.AddField(
            model_name='college',
            name='district',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='college_district', to='district.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='meta_author',
            field=models.CharField(blank=True, help_text='Author information for SEO.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Short description for SEO.', null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for SEO.', null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='meta_tag',
            field=models.CharField(blank=True, help_text='Primary meta tag for SEO.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Title for search engines.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for social sharing.', null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='college/og_image/'),
        ),
        migrations.AddField(
            model_name='college',
            name='og_locale',
            field=models.CharField(blank=True, default='en_US', help_text='Locale for OG tags (e.g., en_US).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title for social sharing.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='og_type',
            field=models.CharField(blank=True, help_text='Type of the OG content (e.g., website, article).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='og_url',
            field=models.URLField(blank=True, help_text='URL to share on social platforms.', null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='affiliated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_affiliation', to='affiliation.affiliation'),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_type', to='collegetype.collegetype'),
        ),
    ]
