# Generated by Django 4.2.15 on 2024-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='scholarships',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
