# Generated by Django 4.2.15 on 2024-09-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0002_college_scholarships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='featured_video',
            field=models.FileField(blank=True, null=True, upload_to='college/featured_videos/'),
        ),
    ]
