# Generated by Django 4.2.15 on 2024-12-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0002_alter_college_options_alter_collegefaqs_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Placement',
        ),
    ]
