# Generated by Django 4.2.15 on 2024-12-04 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coursesandfees', '0003_remove_coursesandfees_college'),
        ('admissionopen', '0001_initial'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collegemanagement', '0002_remove_college_admission_open_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeFaqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='admission_open',
            field=models.ManyToManyField(to='admissionopen.admissionopen'),
        ),
        migrations.AddField(
            model_name='college',
            name='college_admin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='college_admin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='college_gallery',
            field=models.ManyToManyField(to='collegemanagement.collegegallery'),
        ),
        migrations.AddField(
            model_name='college',
            name='courses_and_fees',
            field=models.ManyToManyField(related_name='college_courses_and_fees', to='coursesandfees.coursesandfees'),
        ),
        migrations.AddField(
            model_name='college',
            name='facilities',
            field=models.ManyToManyField(related_name='college_facilities', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='college',
            name='placement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='scholarship',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='scholarships',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collegegallery',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collegegallery',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='college',
            name='faqs',
            field=models.ManyToManyField(to='collegemanagement.collegefaqs'),
        ),
    ]
