# Generated by Django 4.2.15 on 2024-12-05 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collegemanagement', '0002_remove_college_college_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_admin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='college_admin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
