# Generated by Django 4.2.15 on 2024-12-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0003_collegefaqs_placement_college_admission_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='dc_description',
            field=models.TextField(blank=True, help_text='Description for Dublin Core Metadata.', null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='dc_language',
            field=models.CharField(blank=True, default='en', help_text='Language code for Dublin Core Metadata (e.g., en, fr).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='dc_title',
            field=models.CharField(blank=True, help_text='Title for Dublin Core Metadata.', max_length=255, null=True),
        ),
    ]
