# Generated by Django 4.2.15 on 2024-12-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0003_college_college_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='college_admin',
        ),
    ]
