# Generated by Django 4.2.17 on 2025-01-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0003_delete_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='dp_image',
            field=models.ImageField(blank=True, null=True, upload_to='college/dp/'),
        ),
        migrations.AlterField(
            model_name='collegegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='college/gallery/'),
        ),
    ]
