# Generated by Django 4.2.17 on 2025-01-30 04:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0004_alter_college_dp_image_alter_collegegallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='college',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
