# Generated by Django 4.2.15 on 2024-12-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formprogress', '0001_initial'),
        ('collegemanagement', '0004_college_dc_description_college_dc_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='college/brochure/'),
        ),
        migrations.AddField(
            model_name='college',
            name='step_counter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='step_counter', to='formprogress.formstepprogress'),
            preserve_default=False,
        ),
    ]
