# Generated by Django 4.2.15 on 2024-12-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0004_remove_college_college_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='college_gallery',
        ),
        migrations.RemoveField(
            model_name='college',
            name='courses_and_fees',
        ),
    ]
