# Generated by Django 4.2.17 on 2025-01-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0005_college_public_id_college_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
