# Generated by Django 4.2.15 on 2024-12-06 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0005_remove_college_college_gallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='college',
            name='scholarships',
        ),
        migrations.AddField(
            model_name='collegefaqs',
            name='college',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='college_faq', to='collegemanagement.college'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
