# Generated by Django 4.2.15 on 2024-12-06 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0006_remove_college_faqs_remove_college_scholarships_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='college',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
