# Generated by Django 4.2.17 on 2025-01-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0006_alter_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
