# Generated by Django 4.2.17 on 2025-01-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0007_college_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
