# Generated by Django 4.2.17 on 2025-01-31 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formprogress', '0002_alter_formstepprogress_options'),
        ('collegemanagement', '0008_alter_college_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='step_counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='step_counter', to='formprogress.formstepprogress'),
        ),
    ]
