# Generated by Django 4.2.17 on 2025-01-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0009_alter_college_step_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
    ]
