# Generated by Django 4.2.17 on 2025-02-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0010_alter_college_latitude_alter_college_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
