# Generated by Django 4.2.17 on 2025-02-17 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0011_alter_college_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegegallery',
            name='college',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='college_gallery', to='collegemanagement.college'),
            preserve_default=False,
        ),
    ]
