# Generated by Django 4.2.17 on 2025-02-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_alter_socialmedia_options'),
        ('collegemanagement', '0012_collegegallery_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='social_media',
            field=models.ManyToManyField(blank=True, to='socialmedia.socialmedia'),
        ),
    ]
