# Generated by Django 4.2.17 on 2025-02-17 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0012_collegegallery_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegegallery',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_gallery', to='collegemanagement.college'),
        ),
    ]
