# Generated by Django 4.2.17 on 2025-02-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0013_alter_college_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='social_media',
        ),
    ]
