# Generated by Django 4.2.17 on 2025-02-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0014_remove_college_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='college/banner/'),
        ),
    ]
