# Generated by Django 4.2.17 on 2025-02-24 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_rename_is_shown_discipline_is_show'),
        ('collegetype', '0003_alter_collegetype_options'),
        ('affiliation', '0006_affiliation_is_verified'),
        ('district', '0002_alter_district_options'),
        ('facilities', '0003_facility_is_show'),
        ('collegemanagement', '0015_alter_college_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='affiliated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_affiliation', to='affiliation.affiliation'),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_type', to='collegetype.collegetype'),
        ),
        migrations.AlterField(
            model_name='college',
            name='discipline',
            field=models.ManyToManyField(blank=True, null=True, related_name='college_discipline', to='discipline.discipline'),
        ),
        migrations.AlterField(
            model_name='college',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_district', to='district.district'),
        ),
        migrations.AlterField(
            model_name='college',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='facilities',
            field=models.ManyToManyField(blank=True, null=True, related_name='college_facilities', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='college',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='college',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
