# Generated by Django 4.2.17 on 2025-02-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_rename_is_shown_discipline_is_show'),
        ('facilities', '0003_facility_is_show'),
        ('collegemanagement', '0016_alter_college_address_alter_college_affiliated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='discipline',
            field=models.ManyToManyField(blank=True, related_name='college_discipline', to='discipline.discipline'),
        ),
        migrations.AlterField(
            model_name='college',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='college_facilities', to='facilities.facility'),
        ),
    ]
