# Generated by Django 4.2.17 on 2025-02-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0017_alter_college_discipline_alter_college_facilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegegallery',
            old_name='image',
            new_name='images',
        ),
    ]
