# Generated by Django 4.2.17 on 2025-02-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0018_rename_image_collegegallery_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegegallery',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='collegegallery',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='collegegallery',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
