# Generated by Django 4.2.17 on 2025-02-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0019_rename_images_collegegallery_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegegallery',
            name='description',
        ),
    ]
