# Generated by Django 4.2.17 on 2025-02-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0020_remove_collegegallery_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='facilities',
        ),
    ]
