# Generated by Django 4.2.17 on 2025-03-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0021_remove_college_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
