# Generated by Django 4.2.17 on 2025-03-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0022_college_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='google_map_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
