# Generated by Django 4.2.17 on 2025-03-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0023_alter_college_google_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='canonical_url',
            field=models.CharField(blank=True, help_text='Canonical URL to avoid duplicate content.', null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='og_url',
            field=models.CharField(blank=True, help_text='URL to share on social platforms.', null=True),
        ),
    ]
