# Generated by Django 4.2.17 on 2025-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0024_alter_college_canonical_url_alter_college_og_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='website_link',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
