# Generated by Django 4.2.17 on 2025-04-04 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegetype', '0004_alter_collegetype_name'),
        ('district', '0003_rename_is_shown_district_is_show'),
        ('affiliation', '0010_alter_affiliation_district'),
        ('collegemanagement', '0025_alter_college_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='affiliated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_affiliation', to='affiliation.affiliation'),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_type', to='collegetype.collegetype'),
        ),
        migrations.AlterField(
            model_name='college',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_district', to='district.district'),
        ),
    ]
