# Generated by Django 4.2.17 on 2025-04-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliation', '0010_alter_affiliation_district'),
        ('collegemanagement', '0026_alter_college_affiliated_alter_college_college_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='affiliated',
        ),
        migrations.AddField(
            model_name='college',
            name='affiliated',
            field=models.ManyToManyField(blank='True', to='affiliation.affiliation'),
        ),
    ]
