# Generated by Django 4.2.17 on 2025-04-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0027_remove_college_affiliated_college_affiliated'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
