# Generated by Django 4.2.15 on 2024-12-06 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublevel',
            name='level',
        ),
        migrations.AddField(
            model_name='level',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sublevel_level', to='level.sublevel'),
            preserve_default=False,
        ),
    ]
