# Generated by Django 4.2.15 on 2024-12-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'permissions': [('manage_level', 'Manage Level')]},
        ),
        migrations.AlterModelOptions(
            name='sublevel',
            options={'permissions': [('manage_sublevel', 'Manage SubLevel')]},
        ),
    ]
