# Generated by Django 4.2.15 on 2024-12-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_remove_sublevel_level_level_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='level',
        ),
        migrations.AddField(
            model_name='level',
            name='sublevel',
            field=models.ManyToManyField(related_name='sublevel_level', to='level.sublevel'),
        ),
    ]
