# Generated by Django 4.2.17 on 2025-01-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_alter_level_options_alter_sublevel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublevel',
            name='description',
        ),
    ]
