# Generated by Django 4.2.17 on 2025-01-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0003_remove_sublevel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='sublevel',
            field=models.ManyToManyField(blank=True, related_name='sublevel_level', to='level.sublevel'),
        ),
    ]
