# Generated by Django 4.2.17 on 2025-01-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_alter_level_sublevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
