# Generated by Django 4.2.17 on 2025-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0005_level_created_date_level_created_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublevel',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sublevel',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sublevel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
