# Generated by Django 4.2.17 on 2025-03-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0006_sublevel_created_date_sublevel_created_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublevel',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
