# Generated by Django 4.2.17 on 2025-03-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0007_sublevel_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
