# Generated by Django 4.2.17 on 2025-03-21 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0008_level_is_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='sublevel',
        ),
        migrations.AddField(
            model_name='sublevel',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublevel', to='level.level'),
        ),
    ]
