# Generated by Django 4.2.17 on 2025-03-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customgallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgallery',
            name='image',
            field=models.FileField(max_length=500, upload_to='gallery/images'),
        ),
    ]
