# Generated by Django 4.2.15 on 2024-12-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_show', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certification/')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
