# Generated by Django 4.2.17 on 2025-02-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('manage_user', 'Manage User')]},
        ),
    ]
