# Generated by Django 4.2.17 on 2025-02-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupExtension',
        ),
    ]
