# Generated by Django 4.2.15 on 2024-12-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
        ('accounts', '0004_customuser_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_media',
            field=models.ManyToManyField(blank=True, to='socialmedia.socialmedia'),
        ),
    ]
