# Generated by Django 4.2.17 on 2025-02-16 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0011_alter_college_email'),
        ('accounts', '0005_delete_groupextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='collegemanagement.college'),
        ),
    ]
