# Generated by Django 4.2.17 on 2025-02-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0012_collegegallery_college'),
        ('accounts', '0006_alter_customuser_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='collegemanagement.college'),
        ),
    ]
