# Generated by Django 4.2.17 on 2025-03-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_is_verified_customuser_remarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
