# Generated by Django 4.2.17 on 2025-02-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementposition',
            name='placement_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
