# Generated by Django 4.2.17 on 2025-02-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_placementposition_placement_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'permissions': [('manage_advertisement', 'Manage Advertisement')]},
        ),
        migrations.AlterModelOptions(
            name='placementposition',
            options={'permissions': [('manage_placementposition', 'Manage Placement Position')]},
        ),
    ]
