# Generated by Django 4.2.17 on 2025-03-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_advertisement_image_alter_advertisement_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
