# Generated by Django 4.2.17 on 2025-03-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_advertisement_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
