# Generated by Django 4.2.17 on 2025-06-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_advertisement_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='adv_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('result', 'Result')], default='normal', max_length=10),
        ),
    ]
