# Generated by Django 4.2.17 on 2025-06-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_advertisement_adv_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='duration_in_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
