# Generated by Django 4.2.17 on 2025-06-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_advertisement_duration_in_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='duration_in_seconds',
        ),
        migrations.AddField(
            model_name='placementposition',
            name='adv_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('result', 'Result')], default='normal', max_length=10),
        ),
    ]
