# Generated by Django 4.2.17 on 2025-01-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0002_alter_discipline_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='is_shown',
            new_name='is_show',
        ),
    ]
