# Generated by Django 4.2.17 on 2025-03-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duration', '0002_alter_duration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
