# Generated by Django 4.2.15 on 2024-09-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('physical', 'Physical'), ('online', 'Online'), ('hybrid', 'Hybrid')], max_length=10)),
                ('online_seat_limit', models.PositiveIntegerField(default=0)),
                ('offline_seat_limit', models.PositiveIntegerField(default=0)),
                ('is_seat_limit', models.BooleanField(default=False)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('event_links', models.URLField(blank=True, null=True)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('is_registration', models.BooleanField(default=False)),
                ('registration_type', models.CharField(choices=[('paid', 'Paid'), ('free', 'Free')], default='free', max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_type', models.CharField(blank=True, max_length=100, null=True)),
                ('price_country', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_featured_event', models.BooleanField(default=False)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='event_organizer/')),
                ('image_link', models.URLField(blank=True, null=True)),
                ('is_organizer', models.BooleanField(default=False)),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_featured_image', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('event', models.ManyToManyField(related_name='images', to='event.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(related_name='event_category', to='event.eventcategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(related_name='organizer', to='event.eventorganizer'),
        ),
    ]
