# Generated by Django 4.2.15 on 2024-12-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('manage_event', 'Manage Event')]},
        ),
        migrations.AlterModelOptions(
            name='eventgallery',
            options={'permissions': [('manage_event_gallery', 'Manage Event Gallery')]},
        ),
    ]
