# Generated by Django 4.2.15 on 2024-12-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='EventGallery',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='price_country',
            new_name='amount_country',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='price_type',
            new_name='amount_type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='event_type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='is_seat_limit',
            new_name='is_offline_seat_limit',
        ),
        migrations.RenameField(
            model_name='eventorganizer',
            old_name='is_organizer',
            new_name='is_show',
        ),
        migrations.RenameField(
            model_name='eventorganizer',
            old_name='image_link',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_links',
        ),
        migrations.AddField(
            model_name='event',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='dc_description',
            field=models.TextField(blank=True, help_text='Description for Dublin Core Metadata.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='dc_language',
            field=models.CharField(blank=True, default='en', help_text='Language code for Dublin Core Metadata (e.g., en, fr).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='dc_title',
            field=models.CharField(blank=True, help_text='Title for Dublin Core Metadata.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_online_seat_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_author',
            field=models.CharField(blank=True, help_text='Author information for SEO.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Short description for SEO.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for SEO.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_tag',
            field=models.CharField(blank=True, help_text='Primary meta tag for SEO.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Title for search engines.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for social sharing.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='college/og_image/'),
        ),
        migrations.AddField(
            model_name='event',
            name='og_locale',
            field=models.CharField(blank=True, default='en_US', help_text='Locale for OG tags (e.g., en_US).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title for social sharing.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='og_type',
            field=models.CharField(blank=True, help_text='Type of the OG content (e.g., website, article).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='og_url',
            field=models.URLField(blank=True, help_text='URL to share on social platforms.', null=True),
        ),
    ]
