# Generated by Django 4.2.15 on 2024-12-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='college/og_image/'),
        ),
    ]
