# Generated by Django 4.2.17 on 2025-01-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_options_alter_eventgallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
