# Generated by Django 4.2.15 on 2024-12-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_og_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgallery',
            name='event',
        ),
    ]
