# Generated by Django 4.2.17 on 2025-01-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_public_id_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
