# Generated by Django 4.2.17 on 2025-02-04 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgallery',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='event_gallery', to='event.event'),
            preserve_default=False,
        ),
    ]
