# Generated by Django 4.2.17 on 2025-02-04 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventgallery_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgallery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='event.event'),
        ),
    ]
