# Generated by Django 4.2.17 on 2025-02-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_eventgallery_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'permissions': [('manage_eventcategory', 'Manage Event Category')]},
        ),
        migrations.AlterModelOptions(
            name='eventgallery',
            options={'permissions': [('manage_eventgallery', 'Manage Event Gallery')]},
        ),
        migrations.AlterModelOptions(
            name='eventorganizer',
            options={'permissions': [('manage_eventorganizer', 'Manage Event Organizer')]},
        ),
    ]
