# Generated by Django 4.2.17 on 2025-02-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_eventcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
