# Generated by Django 4.2.17 on 2025-02-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_duration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_organizer/'),
        ),
    ]
