# Generated by Django 4.2.17 on 2025-02-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_event_event_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventgallery',
            old_name='image',
            new_name='images',
        ),
    ]
