# Generated by Django 4.2.17 on 2025-02-24 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_rename_image_eventgallery_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgallery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.event'),
        ),
    ]
