# Generated by Django 4.2.17 on 2025-02-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_alter_eventgallery_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventgallery',
            old_name='images',
            new_name='image',
        ),
    ]
