# Generated by Django 4.2.17 on 2025-02-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_alter_eventgallery_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='online_platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
