# Generated by Django 4.2.17 on 2025-03-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_event_online_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
