# Generated by Django 4.2.17 on 2025-03-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_event_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='position',
        ),
        migrations.AddField(
            model_name='eventgallery',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
