# Generated by Django 4.2.17 on 2025-03-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_remove_event_position_eventgallery_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
