# Generated by Django 4.2.17 on 2025-04-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_alter_event_canonical_url_alter_event_og_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
