# Generated by Django 4.2.17 on 2025-04-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='popups/')),
                ('duration_in_seconds', models.IntegerField(default=0)),
                ('is_skipable', models.BooleanField(default=False)),
                ('is_show', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('manage_popup', 'Manage Popup')],
            },
        ),
    ]
