# Generated by Django 4.2.17 on 2025-02-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmindetails', '0002_alter_superadmindetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superadmindetails',
            options={'permissions': [('manage_superadmindetails', 'Manage Super Admin Details')]},
        ),
    ]
