# Generated by Django 4.2.17 on 2025-02-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmindetails', '0003_alter_superadmindetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superadmindetails',
            options={'permissions': [('manage_super_admin_details', 'Manage Super Admin Details')]},
        ),
    ]
