# Generated by Django 4.2.17 on 2025-03-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmindetails', '0005_alter_superadmindetails_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmindetails',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='superadmindetails',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AddField(
            model_name='superadmindetails',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AddField(
            model_name='superadmindetails',
            name='messenger_link',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AddField(
            model_name='superadmindetails',
            name='x_link',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AddField(
            model_name='superadmindetails',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='superadmindetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='superadmindetails',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='superadmindetails',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='superadmindetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
