# Generated by Django 4.2.15 on 2024-12-08 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursemanagement', '0001_initial'),
        ('collegemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesAndFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_admission', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_courses_and_fees', to='collegemanagement.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_and_fees', to='coursemanagement.course')),
            ],
        ),
    ]
