# Generated by Django 4.2.15 on 2024-12-06 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0005_remove_college_college_gallery_and_more'),
        ('coursesandfees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesandfees',
            name='college',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='college_courses_and_fees', to='collegemanagement.college'),
            preserve_default=False,
        ),
    ]
