# Generated by Django 4.2.15 on 2024-12-04 06:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collegemanagement', '0002_remove_college_admission_open_and_more'),
        ('coursemanagement', '0004_remove_course_affiliations_course_affiliation_and_more'),
        ('coursesandfees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesandfees',
            old_name='fee',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='coursesandfees',
            name='course_name',
        ),
        migrations.AddField(
            model_name='coursesandfees',
            name='college',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='courses_and_fees', to='collegemanagement.college'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesandfees',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='courses_and_fees', to='coursemanagement.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesandfees',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesandfees',
            name='is_admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursesandfees',
            name='updated_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
