# Generated by Django 4.2.15 on 2024-12-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesandfees', '0002_rename_fee_coursesandfees_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesandfees',
            name='college',
        ),
    ]
