# Generated by Django 4.2.17 on 2025-02-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesandfees', '0002_alter_coursesandfees_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesandfees',
            options={'permissions': [('manage_coursesandfees', 'Manage courses and fees')]},
        ),
    ]
