# Generated by Django 4.2.17 on 2025-03-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesandfees', '0003_alter_coursesandfees_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesandfees',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
