# Generated by Django 4.2.17 on 2025-03-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesandfees', '0004_alter_coursesandfees_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesandfees',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
