# Generated by Django 4.2.17 on 2025-02-20 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('LogEntry', 'LogEntry'), ('Permission', 'Permission'), ('Group', 'Group'), ('ContentType', 'ContentType'), ('Session', 'Session'), ('CustomUser', 'CustomUser'), ('EmailSetup', 'EmailSetup'), ('Album', 'Album'), ('Gallery', 'Gallery'), ('EventOrganizer', 'EventOrganizer'), ('EventCategory', 'EventCategory'), ('Event', 'Event'), ('EventGallery', 'EventGallery'), ('District', 'District'), ('CollegeType', 'CollegeType'), ('InformationTagging', 'InformationTagging'), ('InformationCategory', 'InformationCategory'), ('Information', 'Information'), ('InformationFiles', 'InformationFiles'), ('InformationGallery', 'InformationGallery'), ('SubLevel', 'SubLevel'), ('Level', 'Level'), ('Affiliation', 'Affiliation'), ('Faculty', 'Faculty'), ('Certification', 'Certification'), ('SocialMedia', 'SocialMedia'), ('CollegeSocialMedia', 'CollegeSocialMedia'), ('Course', 'Course'), ('CourseCurriculumFile', 'CourseCurriculumFile'), ('College', 'College'), ('CollegeFaqs', 'CollegeFaqs'), ('CollegeGallery', 'CollegeGallery'), ('Facility', 'Facility'), ('Discipline', 'Discipline'), ('CoursesAndFees', 'CoursesAndFees'), ('Duration', 'Duration'), ('FormStepProgress', 'FormStepProgress'), ('Inquiry', 'Inquiry'), ('SuperAdminDetails', 'SuperAdminDetails'), ('PlacementPosition', 'PlacementPosition'), ('Advertisement', 'Advertisement'), ('Contact', 'Contact'), ('RequestSubmission', 'RequestSubmission'), ('Notification', 'Notification'), ('Method', 'Method'), ('MyModels', 'MyModels'), ('ModelMethod', 'ModelMethod')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.ManyToManyField(related_name='modelmethod', to='setting.method')),
                ('model_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setting.mymodels')),
            ],
        ),
    ]
