# Generated by Django 4.2.17 on 2025-02-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodels',
            name='model_name',
            field=models.CharField(choices=[('LogEntry', 'LogEntry'), ('Permission', 'Permission'), ('Group', 'Group'), ('ContentType', 'ContentType'), ('Session', 'Session'), ('CustomUser', 'CustomUser'), ('EmailSetup', 'EmailSetup'), ('Album', 'Album'), ('Gallery', 'Gallery'), ('EventOrganizer', 'EventOrganizer'), ('EventCategory', 'EventCategory'), ('Event', 'Event'), ('EventGallery', 'EventGallery'), ('District', 'District'), ('CollegeType', 'CollegeType'), ('InformationTagging', 'InformationTagging'), ('InformationCategory', 'InformationCategory'), ('Information', 'Information'), ('InformationFiles', 'InformationFiles'), ('InformationGallery', 'InformationGallery'), ('SubLevel', 'SubLevel'), ('Level', 'Level'), ('Affiliation', 'Affiliation'), ('Faculty', 'Faculty'), ('Certification', 'Certification'), ('SocialMedia', 'SocialMedia'), ('CollegeSocialMedia', 'CollegeSocialMedia'), ('Course', 'Course'), ('CourseCurriculumFile', 'CourseCurriculumFile'), ('College', 'College'), ('CollegeFaqs', 'CollegeFaqs'), ('CollegeGallery', 'CollegeGallery'), ('Facility', 'Facility'), ('CollegeFacility', 'CollegeFacility'), ('Discipline', 'Discipline'), ('CoursesAndFees', 'CoursesAndFees'), ('Duration', 'Duration'), ('FormStepProgress', 'FormStepProgress'), ('Inquiry', 'Inquiry'), ('SuperAdminDetails', 'SuperAdminDetails'), ('PlacementPosition', 'PlacementPosition'), ('Advertisement', 'Advertisement'), ('Contact', 'Contact'), ('RequestSubmission', 'RequestSubmission'), ('Notification', 'Notification'), ('Method', 'Method'), ('MyModels', 'MyModels'), ('ModelMethod', 'ModelMethod')], max_length=255, unique=True),
        ),
    ]
