# Generated by Django 4.2.17 on 2025-03-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_alter_district_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='is_shown',
            new_name='is_show',
        ),
    ]
