# Generated by Django 4.2.17 on 2025-05-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BucketSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_files', models.IntegerField(default=0)),
                ('new_files', models.IntegerField(default=0)),
                ('updated_files', models.IntegerField(default=0)),
                ('deleted_files', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bucket Sync Log',
                'verbose_name_plural': 'Bucket Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BucketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('size', models.BigIntegerField()),
                ('last_modified', models.DateTimeField()),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('extension', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cache_control', models.CharField(blank=True, max_length=255, null=True)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Bucket File',
                'verbose_name_plural': 'Bucket Files',
                'ordering': ['-last_modified'],
                'indexes': [models.Index(fields=['key'], name='bucketimage_key_74ec87_idx'), models.Index(fields=['extension'], name='bucketimage_extensi_d8cf05_idx'), models.Index(fields=['last_modified'], name='bucketimage_last_mo_c0d4df_idx'), models.Index(fields=['size'], name='bucketimage_size_8923d2_idx')],
            },
        ),
    ]
