# Generated by Django 4.2.17 on 2025-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketimages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BucketSyncLog',
        ),
        migrations.AlterModelOptions(
            name='bucketfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bucket File', 'verbose_name_plural': 'Bucket Files'},
        ),
        migrations.RemoveIndex(
            model_name='bucketfile',
            name='bucketimage_key_74ec87_idx',
        ),
        migrations.RemoveIndex(
            model_name='bucketfile',
            name='bucketimage_extensi_d8cf05_idx',
        ),
        migrations.RemoveIndex(
            model_name='bucketfile',
            name='bucketimage_last_mo_c0d4df_idx',
        ),
        migrations.RemoveIndex(
            model_name='bucketfile',
            name='bucketimage_size_8923d2_idx',
        ),
        migrations.RemoveField(
            model_name='bucketfile',
            name='cache_control',
        ),
        migrations.RemoveField(
            model_name='bucketfile',
            name='etag',
        ),
        migrations.RemoveField(
            model_name='bucketfile',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='bucketfile',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='bucketfile',
            name='key',
        ),
        migrations.RemoveField(
            model_name='bucketfile',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='bucketfile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bucketfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bucket_files/'),
        ),
        migrations.AddField(
            model_name='bucketfile',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bucketfile',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='bucketfile',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
