# Generated by Django 4.2.17 on 2025-05-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketimages', '0002_delete_bucketsynclog_alter_bucketfile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketfile',
            name='url',
        ),
        migrations.AddField(
            model_name='bucketfile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
