# Generated by Django 4.2.17 on 2025-05-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketimages', '0003_remove_bucketfile_url_bucketfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketfile',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
